# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Deploy

on:
  push:
    branches:
      - master  # 或者您要部署的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8  # 或者您要使用的Java版本

      - name: Build with Maven
        run: mvn package --batch-mode

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master  # 或者您要发布到的分支
          folder: target
